# Generated by Django 4.2.6 on 2023-10-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masalalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tekshiruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masalalar.masala')),
            ],
        ),
    ]
